### ISSUE TITLE
Ojua-Nice, Byron - 4-H Resume User Story

### ISSUE THREAD

**Issue by byron-ojua** [Oregon-State-4-H/4HRecordBooks#2]
### **Statement**
As a 4-H Youth, I want to log my 4-H activities so that I can print an automatically generated 4-H Resume.

### **Background**
The 4-H Resume is a live document that is used to keep track of a youth's entire 4-H career. This document can often get long and worn out if the paper copy is not taken care of. This feature is wanted so youth can keep a digital copy of their resume that is automatically updated when a new log is added and can be accessible from anywhere. This feature is intended to be used by youth. The data for this use case is collected as youth log certain sections such as club involvement, projects, volunteer hours, leadership roles, and more. 

### **Sulution/Requirements**
The solution to this user story is to create a feature that allows youth to log their 4-H career, and then generate/download an automatically formatted PDF that has dynamically filled out all of the sections of the 4-H Resume.

#### _**Functional Requirements**_
- As a youth, I should be able to log 4-H Club Involvement, so that it shows up in my 4-H Resume.
- As a youth, I should be able to log 4-H Projects, so that it shows up in my 4-H Resume.
- As a youth, I should be able to log Event/Activity Participation, so that it shows up in my 4-H Resume.
- As a youth, I should be able to log Leadership Roles, so that it shows up in my 4-H Resume.
- As a youth, I should be able to log Community Service, so that it shows up in my 4-H Resume.
- As a youth, I should be able to log Communications, so that it shows up in my 4-H Resume.
- As a youth, I should be able to log Contests/Competitions, so that it shows up in my 4-H Resume.
- As a youth, I should be able to log Recognitions, so that it shows up in my 4-H Resume.
- As a youth, I should be able to print an automatically generated 4-H Resume, so I can hand it in during fair.
- As a youth, I should be able to log into my individual youth account, so that I can access my individual information.

#### _**Non-Functional Requirements**_
- This feature should work on both mobile and PC web browsers.
- The feature should work at any time of the day.
- This feature should be available for all youth.
- The product must comply with The Children's Online Privacy Protection Act (COPPA).

### **Dependencies**
The following tasks block this user story
- Creation of the Database
- CRUD functions between the UI and the Database
- Authentication

### **Task List**
- [ ] Establish connection with database
- [ ] Complete Log Form UI
- [ ] Create CRUD operations for logs
- [ ] Set up 4-H Resume Template
- [ ] Set up Template Renderer

### **Time Estimate**
Once the dependencies blocking this issue have been resolved, this feature should take around four (4) weeks to complete.

### **Open Questions**
There are no open questions at this time.

### **Acceptance Criteria**
- Authenticated users only see their individual data.
- All functional requirements have been met.
- Multiple logs can be added per log category.
- All logs are included when a 4-H Resume report is generated.

### **Definition of Done**
- Acceptance criteria are validated
- A Pull Request has been submitted/approved
- Changes are merged (into the main branch)
- Changes are implemented in all components
- Documentation is updated, incl. deployment instructions if any
- Release notes are updated
